#!/usr/bin/env python3
"""
DAMSA Flux Converter for alplib Integration

This script converts Geant4 simulation output (CSV format) to the format
required by alplib for ALP signal calculation.

Input: CSV files from DAMSA Geant4 simulation
Output: Numpy array format for alplib FluxPrimakoffIsotropic

Usage:
    python flux_converter.py output/photon_flux_target_exit.csv --nprimaries 1000
    
Author: DAMSA Collaboration
"""

import argparse
import numpy as np
import pandas as pd
from pathlib import Path


def load_geant4_flux(csv_path: str) -> pd.DataFrame:
    """
    Load photon flux CSV from Geant4 simulation.
    
    Parameters
    ----------
    csv_path : str
        Path to the photon flux CSV file
        
    Returns
    -------
    pd.DataFrame
        DataFrame with columns: energy_MeV, time_ns, x_mm, y_mm, z_mm, 
                               px, py, pz, weight, trackID, eventID
    """
    df = pd.read_csv(csv_path)
    return df


def convert_to_alplib_flux(df: pd.DataFrame, 
                           n_primaries: int,
                           beam_current_uA: float = 62.5,
                           energy_bins: np.ndarray = None) -> np.ndarray:
    """
    Convert Geant4 photon data to alplib flux format.
    
    Parameters
    ----------
    df : pd.DataFrame
        Photon data from Geant4 (energy_MeV column required)
    n_primaries : int
        Number of primary electrons simulated
    beam_current_uA : float
        Beam current in microamperes (default: 62.5 μA)
    energy_bins : np.ndarray, optional
        Custom energy bin edges in MeV. If None, uses 1 MeV bins from 0 to max energy.
        
    Returns
    -------
    np.ndarray
        2D array with shape (n_bins, 2): [[energy_MeV, rate_per_second], ...]
    """
    # Calculate electrons per second from beam current
    # I = Q/t, electrons/s = I / e
    e_charge = 1.602176634e-19  # Coulombs
    beam_current = beam_current_uA * 1e-6  # Convert to Amperes
    electrons_per_second = beam_current / e_charge
    
    # Scale factor: photons per electron * electrons per second
    scale_factor = electrons_per_second / n_primaries
    
    energies = df['energy_MeV'].values
    weights = df['weight'].values if 'weight' in df.columns else np.ones(len(energies))
    
    # Create energy bins
    if energy_bins is None:
        max_energy = np.ceil(energies.max())
        energy_bins = np.arange(0, max_energy + 1, 1.0)  # 1 MeV bins
    
    # Histogram the energies
    counts, bin_edges = np.histogram(energies, bins=energy_bins, weights=weights)
    
    # Bin centers
    bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])
    
    # Convert counts to rate (photons per second)
    rates = counts * scale_factor
    
    # Create output array
    flux = np.column_stack([bin_centers, rates])
    
    # Remove empty bins
    flux = flux[flux[:, 1] > 0]
    
    return flux


def convert_to_alplib_unbinned(df: pd.DataFrame,
                                n_primaries: int,
                                beam_current_uA: float = 62.5) -> np.ndarray:
    """
    Convert Geant4 photon data to unbinned alplib format.
    
    This provides individual photon energies with weights scaled to rate,
    useful for detailed spectrum analysis.
    
    Parameters
    ----------
    df : pd.DataFrame
        Photon data from Geant4
    n_primaries : int
        Number of primary electrons simulated
    beam_current_uA : float
        Beam current in microamperes
        
    Returns
    -------
    np.ndarray
        2D array with shape (n_photons, 2): [[energy_MeV, weight_per_second], ...]
    """
    e_charge = 1.602176634e-19
    beam_current = beam_current_uA * 1e-6
    electrons_per_second = beam_current / e_charge
    scale_factor = electrons_per_second / n_primaries
    
    energies = df['energy_MeV'].values
    weights = df['weight'].values if 'weight' in df.columns else np.ones(len(energies))
    
    # Scale weights to rate
    scaled_weights = weights * scale_factor
    
    return np.column_stack([energies, scaled_weights])


def save_alplib_flux(flux: np.ndarray, output_path: str):
    """
    Save flux data in alplib-compatible format.
    
    Parameters
    ----------
    flux : np.ndarray
        2D array [[energy_MeV, rate_per_second], ...]
    output_path : str
        Output file path (text format)
    """
    header = """# Photon flux for alplib input
# Generated by DAMSA flux_converter.py
# Format: energy_MeV, rate_per_second
# Usage in alplib:
#   flux_data = np.loadtxt('this_file.txt', delimiter=',')
#   flux = FluxPrimakoffIsotropic(photon_flux=flux_data, ...)
"""
    np.savetxt(output_path, flux, delimiter=',', header=header, 
               fmt=['%.3f', '%.6e'], comments='')
    print(f"Saved alplib flux to: {output_path}")


def save_numpy_flux(flux: np.ndarray, output_path: str):
    """
    Save flux data as numpy binary file for direct loading.
    
    Parameters
    ----------
    flux : np.ndarray
        2D array [[energy_MeV, rate_per_second], ...]
    output_path : str
        Output file path (.npy format)
    """
    np.save(output_path, flux)
    print(f"Saved numpy flux to: {output_path}")


def print_flux_summary(flux: np.ndarray, df: pd.DataFrame = None):
    """Print summary statistics of the flux."""
    print("\n=== Flux Summary ===")
    print(f"Number of energy bins: {len(flux)}")
    print(f"Energy range: {flux[:, 0].min():.1f} - {flux[:, 0].max():.1f} MeV")
    print(f"Total rate: {flux[:, 1].sum():.3e} photons/second")
    print(f"Peak rate at: {flux[np.argmax(flux[:, 1]), 0]:.1f} MeV")
    print(f"Peak rate: {flux[:, 1].max():.3e} photons/second")
    
    if df is not None:
        print(f"\nOriginal data:")
        print(f"  Total photons: {len(df)}")
        print(f"  Mean energy: {df['energy_MeV'].mean():.2f} MeV")
        print(f"  Median energy: {df['energy_MeV'].median():.2f} MeV")
        if 'time_ns' in df.columns:
            print(f"  Time range: {df['time_ns'].min():.2f} - {df['time_ns'].max():.2f} ns")
    print("===================\n")


def apply_cuts(df: pd.DataFrame,
               min_energy: float = None,
               max_energy: float = None,
               max_angle: float = None,
               max_time: float = None) -> pd.DataFrame:
    """
    Apply physics cuts to photon data.
    
    Parameters
    ----------
    df : pd.DataFrame
        Input photon data
    min_energy : float, optional
        Minimum photon energy in MeV
    max_energy : float, optional
        Maximum photon energy in MeV
    max_angle : float, optional
        Maximum angle from beam axis in degrees
    max_time : float, optional
        Maximum arrival time in ns (for background rejection)
        
    Returns
    -------
    pd.DataFrame
        Filtered photon data
    """
    mask = np.ones(len(df), dtype=bool)
    
    if min_energy is not None:
        mask &= df['energy_MeV'] >= min_energy
        print(f"Applied min_energy cut: {min_energy} MeV")
        
    if max_energy is not None:
        mask &= df['energy_MeV'] <= max_energy
        print(f"Applied max_energy cut: {max_energy} MeV")
        
    if max_angle is not None:
        # Calculate angle from momentum direction
        if all(col in df.columns for col in ['px', 'py', 'pz']):
            cos_theta = df['pz']  # Assuming unit vector, pz = cos(theta)
            angle_deg = np.degrees(np.arccos(np.clip(cos_theta, -1, 1)))
            mask &= angle_deg <= max_angle
            print(f"Applied max_angle cut: {max_angle} degrees")
        else:
            print("Warning: Cannot apply angle cut - momentum columns not found")
            
    if max_time is not None:
        if 'time_ns' in df.columns:
            mask &= df['time_ns'] <= max_time
            print(f"Applied max_time cut: {max_time} ns")
        else:
            print("Warning: Cannot apply time cut - time_ns column not found")
    
    filtered = df[mask].copy()
    print(f"Photons after cuts: {len(filtered)} / {len(df)} ({100*len(filtered)/len(df):.1f}%)")
    
    return filtered


def main():
    parser = argparse.ArgumentParser(
        description='Convert DAMSA Geant4 photon flux to alplib format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic conversion
  python flux_converter.py output/photon_flux_target_exit.csv --nprimaries 1000
  
  # With energy cuts
  python flux_converter.py output/photon_flux_target_exit.csv --nprimaries 1000 \\
      --min-energy 10 --max-energy 8000
      
  # With angular acceptance cut (20 degrees)
  python flux_converter.py output/photon_flux_target_exit.csv --nprimaries 1000 \\
      --max-angle 20
      
  # Custom beam current
  python flux_converter.py output/photon_flux_target_exit.csv --nprimaries 1000 \\
      --beam-current 100.0
"""
    )
    
    parser.add_argument('input', type=str, help='Input CSV file from Geant4')
    parser.add_argument('--nprimaries', '-n', type=int, required=True,
                        help='Number of primary electrons simulated')
    parser.add_argument('--output', '-o', type=str, default=None,
                        help='Output file path (default: input_alplib.txt)')
    parser.add_argument('--beam-current', type=float, default=62.5,
                        help='Beam current in μA (default: 62.5)')
    parser.add_argument('--bin-width', type=float, default=1.0,
                        help='Energy bin width in MeV (default: 1.0)')
    parser.add_argument('--min-energy', type=float, default=None,
                        help='Minimum photon energy in MeV')
    parser.add_argument('--max-energy', type=float, default=None,
                        help='Maximum photon energy in MeV')
    parser.add_argument('--max-angle', type=float, default=None,
                        help='Maximum angle from beam axis in degrees')
    parser.add_argument('--max-time', type=float, default=None,
                        help='Maximum arrival time in ns')
    parser.add_argument('--save-numpy', action='store_true',
                        help='Also save as numpy binary file')
    parser.add_argument('--unbinned', action='store_true',
                        help='Output unbinned (per-photon) data')
    
    args = parser.parse_args()
    
    # Load data
    print(f"Loading: {args.input}")
    df = load_geant4_flux(args.input)
    print(f"Loaded {len(df)} photons")
    
    # Apply cuts
    if any([args.min_energy, args.max_energy, args.max_angle, args.max_time]):
        df = apply_cuts(df, 
                       min_energy=args.min_energy,
                       max_energy=args.max_energy,
                       max_angle=args.max_angle,
                       max_time=args.max_time)
    
    # Convert to alplib format
    if args.unbinned:
        flux = convert_to_alplib_unbinned(df, args.nprimaries, args.beam_current)
    else:
        # Create energy bins
        max_energy = np.ceil(df['energy_MeV'].max())
        energy_bins = np.arange(0, max_energy + args.bin_width, args.bin_width)
        flux = convert_to_alplib_flux(df, args.nprimaries, args.beam_current, energy_bins)
    
    # Print summary
    print_flux_summary(flux, df)
    
    # Determine output path
    if args.output is None:
        input_path = Path(args.input)
        output_path = input_path.parent / f"{input_path.stem}_alplib.txt"
    else:
        output_path = Path(args.output)
    
    # Save outputs
    save_alplib_flux(flux, str(output_path))
    
    if args.save_numpy:
        npy_path = output_path.with_suffix('.npy')
        save_numpy_flux(flux, str(npy_path))
    
    print("Done!")


if __name__ == '__main__':
    main()
